---
version: '3'
services:
  web-proxy:
    image: venkynagidi/two:mydockerimage
    ports:
      - "3000:80"
    networks:
      - "network-one"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  network-one:
    driver: bridge
